package Vista;

import Controlador.cls_conexionbd;
import Modelo.Cuentas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexis
 */
public class CuentasBanco extends javax.swing.JFrame {

    /**
     * Creates new form CuentasBanco
     */
    public CuentasBanco() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    cls_conexionbd conexbd = new cls_conexionbd();
    Connection conexion = conexbd.conectarBB();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Cuentas_BancariasPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Cuentas_BancariasPU").createEntityManager();
        cuentasQuery = java.beans.Beans.isDesignTime() ? null : Cuentas_BancariasPUEntityManager.createQuery("SELECT c FROM Cuentas c");
        cuentasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cuentasQuery.getResultList();
        cuentasQuery1 = java.beans.Beans.isDesignTime() ? null : Cuentas_BancariasPUEntityManager.createQuery("SELECT c FROM Cuentas c");
        cuentasList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cuentasQuery1.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtTCuenta = new javax.swing.JTextField();
        txtMov = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btAgregar = new javax.swing.JButton();
        txtCuenta = new javax.swing.JTextField();
        jbpresDt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtConsul = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbCambiardatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Cuentas Bancarias");

        jLabel2.setText("Nº de Cuenta");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Tipo de Cuenta:");

        jLabel5.setText("Movimiento:");

        jLabel6.setText("Fecha:");

        jLabel7.setText("Saldo:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        btAgregar.setText("AGREGAR");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });

        jbpresDt.setText("Presentar Datos");
        jbpresDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpresDtActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cuentasList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${saldo}"));
        columnBinding.setColumnName("Saldo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movimiento}"));
        columnBinding.setColumnName("Movimiento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoCuenta}"));
        columnBinding.setColumnName("Tipo Cuenta");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliente}"));
        columnBinding.setColumnName("Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroCuenta}"));
        columnBinding.setColumnName("Numero Cuenta");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Consulta Por numero de cuenta:");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbCambiardatos.setText("Cambiar datos");
        jbCambiardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCambiardatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbpresDt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(57, 57, 57))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTCuenta)
                                    .addComponent(txtCliente)
                                    .addComponent(txtMov)
                                    .addComponent(txtFecha)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtCuenta))
                                .addGap(162, 162, 162)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConsul, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAgregar)
                        .addGap(116, 116, 116)
                        .addComponent(jbCambiardatos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtConsul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregar)
                    .addComponent(jbCambiardatos))
                .addGap(35, 35, 35)
                .addComponent(jbpresDt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
        int numero_cuenta = Integer.parseInt(txtCuenta.getText());
        String cliente = txtCliente.getText();
        String tipo_cuenta = txtTCuenta.getText();
        String movimiento = txtMov.getText();
        String Fecha = txtFecha.getText();
        String saldo = txtSaldo.getText();
        Cuentas cuentas = new Cuentas(numero_cuenta, cliente, tipo_cuenta, movimiento, Fecha, saldo);

        try {
            PreparedStatement insertar = conexion.prepareStatement("INSERT INTO Cuentas (numero_cuenta, cliente, tipo_cuenta, movimiento, fecha, saldo) VALUES(?,?,?,?,?,?)");

            insertar.setInt(1, numero_cuenta);
            insertar.setString(2, cliente);
            insertar.setString(3, tipo_cuenta);
            insertar.setString(4, movimiento);
            insertar.setString(5, Fecha);
            insertar.setString(6, saldo);

            int d = insertar.executeUpdate();
            if (d > 0) {
                JOptionPane.showMessageDialog(null, "   Registro Guardado con éxito");
                borrarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "   Registro no Guardado");
            }

        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }

    void borrarDatos() {
        txtCuenta.setText("");
        txtCliente.setText("");
        txtTCuenta.setText("");
        txtMov.setText("");
        txtFecha.setText("");
        txtSaldo.setText("");
    }
    
    void consultaN_Cuenta(int numero_cuenta) {
        try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select numero_cuenta, cliente, tipo_cuenta, movimiento, fecha, saldo from cuentas where NUMERO_CUENTA ='" + numero_cuenta + "'");
            if (registro.next() == true) {
                txtCuenta.setText(registro.getString("numero_cuenta"));
                txtCliente.setText(registro.getString("Cliente"));
                txtTCuenta.setText(registro.getString("Tipo_cuenta"));
                txtMov.setText(registro.getString("Movimiento"));
                txtFecha.setText(registro.getString("Fecha"));
                txtSaldo.setText(registro.getString("Saldo"));

            } else {
                JOptionPane.showMessageDialog(null, "No existe un artículo con dicho código");
            }
            conexion.close();
        } catch (SQLException ex) {
            setTitle(ex.toString());
        }

    }//GEN-LAST:event_btAgregarActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void jbpresDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpresDtActionPerformed
         //TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NUMERO_CUENTA");
        modelo.addColumn("CLIENTE");
        modelo.addColumn("TIPO_CUENTA");
        modelo.addColumn("MOVIMIENTO");
        modelo.addColumn("FECHA");
        modelo.addColumn("SALDO");
        //DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
        try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select * from CUENTAS");
            while (registro.next()) {
                Vector vector = new Vector();
                vector.add(registro.getInt(1));
                vector.add(registro.getString(2));
                vector.add(registro.getString(3));
                vector.add(registro.getString(4));
                vector.add(registro.getString(5));
                vector.add(registro.getString(6));
                modelo.addRow(vector);
            }

            jTable1.setModel(modelo);  //!!!!!!!!!!!!!!!
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jbpresDtActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(txtConsul.getText().trim());
        consultaN_Cuenta(n);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbCambiardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCambiardatosActionPerformed
        // TODO add your handling code here:
//        try {
//            Statement comando = conexion.createStatement();
//            ResultSet registro = comando.executeQuery("select numero_cuenta, cliente, tipo_cuenta, movimiento, fecha, saldo from cuentas where NUMERO_CUENTA ='" + numero_cuenta + "'");
//           if (registro.next() == true) {
//                txtCuenta.setText(registro.getString("numero_cuenta"));
//                txtCliente.setText(registro.getString("Cliente"));
//                txtTCuenta.setText(registro.getString("Tipo_cuenta"));
//                txtMov.setText(registro.getString("Movimiento"));
//                txtFecha.setText(registro.getString("Fecha"));
//                txtSaldo.setText(registro.getString("Saldo"));
//
//            } else {
//                JOptionPane.showMessageDialog(null, "No existe un artículo con dicho código");
//            }
//            conexion.close();
//        } catch (SQLException ex) {
//            setTitle(ex.toString());
//        }
        
    }//GEN-LAST:event_jbCambiardatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentasBanco.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentasBanco.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentasBanco.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentasBanco.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentasBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Cuentas_BancariasPUEntityManager;
    private javax.swing.JButton btAgregar;
    private java.util.List<Vista.Cuentas> cuentasList;
    private java.util.List<Vista.Cuentas> cuentasList1;
    private javax.persistence.Query cuentasQuery;
    private javax.persistence.Query cuentasQuery1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCambiardatos;
    private javax.swing.JButton jbpresDt;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtConsul;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMov;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTCuenta;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
